#!/usr/bin/env python3
"""Mithraeum icon system — one vault, one block, five products.

The mark is a mithraeum arch with a block inside it: the box (箱) *is* the
cursor, the thing that is alive under the vault. The arch never changes. The
block is the only variable — its fill, its treatment, its colour — so the family
reads as a family and each product still reads at 60px, which is the size that
actually decides an icon: an iOS home screen, a macOS dock, a GitHub avatar.

Everything is geometry. No text, no fonts: a wordmark is illegible at icon sizes
and a font dependency makes the render machine-specific. Lettered "plate"
versions belong in a README, not on a home screen.

    python3 make-icons.py     # write the SVG masters
    sh build.sh               # rasterise PNG + icns + ico into each project
"""

import os

OUT = os.path.dirname(os.path.abspath(__file__))

# Shared palette — the values the CLIs, the editor themes and the site all use.
VOID  = "#0f0e0a"
FRAME = "#2a2722"
GOLD  = "#b89656"
BONE  = "#d8d2c2"
PHOS  = "#7a8a3a"

S    = 512                   # master canvas
PAD  = 44                    # frame inset; keeps everything inside iOS masking
CX   = S // 2
AW   = 250                   # arch width
AL, AR = CX - AW // 2, CX + AW // 2
ATOP, ABOT = 150, 392        # crown and floor
R    = AW // 2               # springline radius

BX, BY, BW, BH = CX - 46, 252, 92, 118      # the block


def chassis(keystone=True):
	"""Void plate, hairline frame, gold corner ticks, the vault, the keystone."""
	t = 40
	ticks = []
	for (x, y, dx, dy) in ((PAD, PAD, 1, 1), (S - PAD, PAD, -1, 1),
	                       (PAD, S - PAD, 1, -1), (S - PAD, S - PAD, -1, -1)):
		ticks.append(f'<line x1="{x}" y1="{y}" x2="{x + dx * t}" y2="{y}"/>')
		ticks.append(f'<line x1="{x}" y1="{y}" x2="{x}" y2="{y + dy * t}"/>')
	# Keystone sits clear of the arch stroke — at 60px they merge otherwise.
	ks = (f'<circle cx="{CX}" cy="{ATOP - 26}" r="15" fill="{GOLD}"/>'
	      if keystone else '')
	return f'''<rect width="{S}" height="{S}" fill="{VOID}"/>
	<rect width="{S}" height="{S}" fill="url(#glow)"/>
	<rect x="{PAD}" y="{PAD}" width="{S - 2 * PAD}" height="{S - 2 * PAD}"
	      fill="none" stroke="{FRAME}" stroke-width="2"/>
	<g stroke="{GOLD}" stroke-width="5" stroke-linecap="square">
		{"".join(ticks)}
	</g>
	<path d="M{AL} {ABOT} V{ATOP + R} A{R} {R} 0 0 1 {AR} {ATOP + R} V{ABOT}"
	      fill="none" stroke="{BONE}" stroke-width="10" stroke-linejoin="round"/>
	<line x1="{AL - 42}" y1="{ABOT}" x2="{AR + 42}" y2="{ABOT}"
	      stroke="{BONE}" stroke-width="10" stroke-linecap="round"/>
	{ks}'''


def b_agent():
	"""hako — a solid gold cursor. The family's base form."""
	return f'<rect x="{BX}" y="{BY}" width="{BW}" height="{BH}" fill="{GOLD}"/>'


def b_editor():
	"""hake — the cursor on a line of text. The editor is the text one."""
	return (f'<rect x="{BX}" y="{BY - 6}" width="{BW}" height="{BH - 22}" fill="{PHOS}"/>'
	        f'<line x1="{CX - 62}" y1="{BY + BH - 4}" x2="{CX + 62}" y2="{BY + BH - 4}" '
	        f'stroke="{BONE}" stroke-width="12" stroke-linecap="round" opacity="0.8"/>')


def b_engine():
	"""hakm — the block as quantised strata: weights on disk, layers in memory."""
	bars = []
	for i in range(3):
		y = BY + 22 + i * 34
		bars.append(f'<line x1="{BX + 14}" y1="{y}" x2="{BX + BW - 14}" y2="{y}"/>')
	return (f'<rect x="{BX}" y="{BY}" width="{BW}" height="{BH}" fill="none" '
	        f'stroke="{PHOS}" stroke-width="10"/>'
	        f'<g stroke="{PHOS}" stroke-width="11" stroke-linecap="round">{"".join(bars)}</g>')


def b_studio():
	"""studio — a hollow block: a pane in the vault, not a cursor."""
	return (f'<rect x="{BX}" y="{BY}" width="{BW}" height="{BH}" fill="none" '
	        f'stroke="{GOLD}" stroke-width="16"/>')


def b_org():
	"""mithraeum — the empty vault. The parent holds no product."""
	return (f'<line x1="{CX - 86}" y1="{ATOP + R}" x2="{CX + 86}" y2="{ATOP + R}" '
	        f'stroke="{FRAME}" stroke-width="4" stroke-dasharray="7 11"/>')


PRODUCTS = {
	"mithraeum": (b_org,    True),
	"hake":      (b_editor, True),
	"hako":      (b_agent,  True),
	"hakm":      (b_engine, True),
	"studio":    (b_studio, True),
}


def svg(name, block, keystone):
	return f'''<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {S} {S}" width="{S}" height="{S}">
	<!-- mithraeum icon system — generated by assets/icons/make-icons.py, do not hand-edit.
	     {name}: the vault, and the block inside it. -->
	<defs>
		<radialGradient id="glow" cx="32%" cy="18%">
			<stop offset="0" stop-color="#ffffff" stop-opacity="0.05"/>
			<stop offset="1" stop-color="#ffffff" stop-opacity="0"/>
		</radialGradient>
	</defs>
	{chassis(keystone)}
	{block()}
</svg>
'''


if __name__ == "__main__":
	for name, (block, keystone) in PRODUCTS.items():
		path = os.path.join(OUT, f"{name}.svg")
		with open(path, "w") as f:
			f.write(svg(name, block, keystone))
		print(f"wrote {name}.svg")
